### PR TITLE
Build wheels for Python 3.11 and 3.12, remove Python 3.7 builds and support

### LINKED ISSUE #49: Installation problem and wheels for Python 3.11 and 3.12
Could wheels be provided for Python 3.11 and just-released 3.12 to ease installation?

Also, I was unable to install Omikuji on Python 3.11 at all, due to a regexp error by Milksnake, see https://github.com/NatLibFi/Annif/issues/703#issuecomment-1614513903.

It might be that there will not be a new Milksnake release including the fix for this; it has alredy been some time since the fix has been merged to master. So, a least-effort option on Omikuji side seems to be to install current Milksnake master. (I checked [this works](https://github.com/juhoinkinen/omikuji/commit/9f30e2ceefdad8d312e8d34357caf7ed81920ff4).)

Alternatively, some projects have [replaced Milksnake by Maturin](https://github.com/pyocd/cmsis-pack-manager/pull/195), which might be a more involved, but also a long-term solution.

BTW, you might want also to update the [classifiers for supported Python versions in `setup.py`](https://github.com/tomtung/omikuji/blob/master/setup.py#L51C5-L55C49) too.

### PR DESCRIPTION
**Pull request by juhoinkinen**
This hopefully makes the CI service build wheels also for Python 3.11 and 3.12. Closes #49.

Also pins milksnake dependency to >=0.1.6.

The macOS-1015 image is no longer available on [Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software), so the macOS job is updated to use macOS-11 image. However, because ["macOS version numbering isn’t so simple"](https://eclecticlight.co/2020/08/13/macos-version-numbering-isnt-so-simple/), if not setting `SYSTEM_VERSION_COMPAT: 0`, pip would [not find the correct wheel file](https://yubingdong.visualstudio.com/omikuji/_build/results?buildId=228&view=logs&j=b6c0e7ff-db6a-5e28-6ba3-b6890b5313bc&t=0f3ca4ad-d71a-59d8-12a2-93f7a2e9a059) for Python 3.7-3.9.

### CODE REVIEW

**Comment by juhoinkinen** [comment]
I could not get the builds on Windows with Python 3.11 and 3.12 to work. The problem seems to be that Milksnake does not detect the platform correctly, but gives "None" in place of ".cp311-win_amd64" (in Python 3.11), which ends up in the library file name ([from build logs](https://yubingdong.visualstudio.com/omikuji/_build/results?buildId=232&view=logs&j=7d81ff55-2de5-5a0b-64ce-7d9ee7ba993c&t=78f7645a-26fc-56a3-987a-c03d3dd1653a&l=1930)): 

    Creating library build\temp.win-amd64-cpython-311\Release\build\temp.win-amd64-cpython-311\_libomikuji__libNone.lib and object build\temp.win-amd64-cpython-311\Release\build\temp.win-amd64-cpython-311\_libomikuji__libNone.exp

[This](https://github.com/getsentry/milksnake/blob/421cc1ffab4d76d01366240c087ffb30d63b744c/milksnake/setuptools_ext.py#L221-L225) looks like where Milksnake is generating the library filename.

For our use the wheels for Windows on Python 3.11 and 3.12 are not so much needed, only the manylinux wheels. Maybe the Windows Python 3.11 and 3.12 builds could be just left out for now? 

Also, the manylinux build for Python 3.7 does not work, but 3.7 being EOLed, I could consider dropping those builds from all platforms.

**Comment by tomtung** [comment]
Thanks so much for looking into this! I understand how time-consuming it can be to tweak and debug the build pipeline sometimes, so I really appreciate the help!

> For our use the wheels for Windows on Python 3.11 and 3.12 are not so much needed, only the manylinux wheels. Maybe the Windows Python 3.11 and 3.12 builds could be just left out for now?

> Also, the manylinux build for Python 3.7 does not work, but 3.7 being EOLed, I could consider dropping those builds from all platforms.

Yeah I think that's fine for now; please feel free to remove these variants before merge.

I was hoping that maturin could help automagically solve some of these complexities by relying more on the rust build system, but never got around to try that. For now this is good enough.

**Comment by juhoinkinen** [comment]
The failures of the latest jobs seem nonrecurring and unimportant (some pull rate limit and random hang). I was not authorized to rerun them.

**Comment by tomtung** [comment]
Thanks! The Python 3.12 build for Linux is still failing after retry, and I think the reason seems to not be spurious. The error message is:
```
##[error]Failed to download Python from the Github Actions python registry (https://github.com/actions/python-versions). Error: Error: Could not find Python matching spec 3.12 (x64) in the python-versions registry. Beware that only systems listed in the Github Actions python versions manifest (https://github.com/actions/python-versions/blob/main/versions-manifest.json) are fit for downloading python on-flight. Also, proxy is not supported.
##[error]Version spec 3.12 for architecture x64 did not match any version in Agent.ToolsDirectory.
Versions in /__t:

3.10.13 (x64)
3.11.6 (x64)
3.7.17 (x64)
3.8.18 (x64)
3.9.18 (x64)
If this is a Microsoft-hosted agent, check that this image supports side-by-side versions of Python at https://aka.ms/hosted-agent-software.
If this is a self-hosted agent, see how to configure side-by-side Python versions at https://go.microsoft.com/fwlink/?linkid=871498.
```

After some debugging, the cause seems to be that Python 3.12 isn't yet included as part of the Linux runner image. If I understand correctly, the list of currently supported Python versions are listed [here](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#python) (which are consistent with the ones listed in the error message).

I guess if we want to use 3.12, we'd need to install it on-the-fly somehow. Version 3.12.0 is indeed listed in the https://github.com/actions/python-versions/blob/main/versions-manifest.json file mentioned in the error message. I wonder if it only accepts full version numbers (i.e. 3.12.0 rather than 3.12)? I'll try changing it later when I get around to it.

**Comment by juhoinkinen** [comment]
I thought the recent failure of the Python 3.12 build for Linux was a one-time problem, because on Tuesday the build worked consistently, e.g. [this build](https://yubingdong.visualstudio.com/omikuji/_build/results?buildId=231&view=logs&s=deacb120-a5f8-5248-b83a-ff983ef5c9b1&j=26547767-f614-5b81-72f7-cc6b013c1b4d).

The reason seems to be that on Tuesday Python 3.12 actually was available in the runner image, but was then removed from the image: https://github.com/actions/runner-images/issues/8626

**Comment by tomtung** [comment]
It finally passes! I'll merge it now, and try release it over the weekend on pypi. Thanks again for figuring this out!

**Pull request merged**
